In [1]:
# import necessary packages
import pandas as pd
from plotnine import *
import numpy as np

# Heart dataset

* Are high blood pressure and age related?

In [2]:
heart = pd.read_csv("https://raw.githubusercontent.com/katherinehansen2/CPSC392Hansen/main/data/heart_failure_clinical_records_dataset.csv")
heart.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

# Fifa Dataset

Use ggplot/plotnine to make a graph to answer each question
1. Load the following dataset
`fifa = pd.read_csv("https://raw.githubusercontent.com/katherinehansen2/CPSC392Hansen/main/data/players_15.csv")`

Dataset from [Kaggle](https://www.kaggle.com/datasets/stefanoleone992/fifa-20-complete-player-dataset)
2. What is the distribution of ages in FIFA20? Make a histogram of ages.
3. Do right-footed players weigh more than left-footed players?
4. Is there a height difference between the clubs Chelsea and Manchester United?
5. Is there a difference in the relationship between height and weight for people born in each of the 12 months? Code is provided below to add a month_born column
6. Is there a difference in weight between players with different body_types?
7. Create a new column called `bmi`. The forumla for BMI is
$$ BMI = \frac{weight(kg)}{height(m)^2}$$

Plot a histogram of all BMIs in the dataset. Add a dashed line at the mean BMI using `+ geom_vline(xintercept = mean, linetype = "dashed", size = 3)`, where mean is the mean BMI (which you'll need to calculate)
8. What is the relationship between height and weight for each body type?
9. Is there an association between jersey number and age?
10. Create a column called `name_len` that counts the number of characters in each player's `long_name` (excluding spaces). Then create a histogram off `name_len` and add a theme. What is the typical range of `name_len`?

In [10]:
# LOAD DATASET HERE

In [9]:
# short_name example
fifa["name_len_short"] = fifa["short_name"].str.len()

fifa["name_len_short"]

0         8
1        17
2         9
3        14
4         8
         ..
15460     9
15461    10
15462     8
15463     9
15464    10
Name: name_len_short, Length: 15465, dtype: int64

In [13]:
# get month born
fifa["month_born"] = fifa["dob"].str.extract(r'-([0-9][0-9])-')

# Bad data visualizations

Load in the heart.csv dataset from GitHub into a df named heart_data.

Make the worst bad data visualization you can - but make sure it's not a wrong visualization! What can you add to make it worse? Clutter? Reduce contrast? Make it inaccessible? Make the message hard to understand? Have fun with it, and discuss with your group WHY the things you are adding make a bad visualization

In [15]:
heart_data = pd.read_csv("https://raw.githubusercontent.com/katherinehansen2/CPSC392Hansen/main/data/heart.csv")
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1